default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_articles_development


test:
  <<: *default
  database: search_articles_test

production:
  <<: *default
  database: search_articles_production
  username: search_articles
  password: <%= ENV["SEARCH_ARTICLES_DATABASE_PASSWORD"] %>
